version: "3"

includes:
  inspect:
    taskfile: "../inspect.yaml"
  gcloud_run_services:
    taskfile: "../gcloud/run_services.yaml"
  gcloud_run_revisions:
    taskfile: "../gcloud/run_revisions.yaml"

tasks:
  delete_configuration:
    dir: "{{.USER_WORKING_DIR}}"
    requires:
      vars:
        - GCP_PROJECT_ID
    cmds:
      - task: inspect:delete_configuration
        vars:
          GCP_PROJECT_ID:
            ref: .GCP_PROJECT_ID

  activate_configuration:
    dir: "{{.USER_WORKING_DIR}}"
    requires:
      vars:
        - GCP_PROJECT_ID
        - USER_ACCOUNT
        - AUTHORIZATION_TOKEN
    cmds:
      - task: inspect:activate_configuration
        vars:
          GCP_PROJECT_ID:
            ref: .GCP_PROJECT_ID
          USER_ACCOUNT:
            ref: .USER_ACCOUNT
          AUTHORIZATION_TOKEN:
            ref: .AUTHORIZATION_TOKEN

  describe_*:
    dir: "{{.USER_WORKING_DIR}}"
    requires:
      vars:
        - GCP_PROJECT_ID
        - CLOUD_RUN_ASSET_NAMES
        - CLOUD_RUN_SERVICES
    vars:
      _RUN_ASSET_TYPE: "{{index .MATCH 0}}"
    cmds:
      - for:
          var: CLOUD_RUN_ASSET_NAMES
          split: ","
          as: CLOUD_RUN_ASSET_NAME
        task: gcloud_run_{{._RUN_ASSET_TYPE}}:describe
        vars:
          GCP_PROJECT:
            ref: .GCP_PROJECT_ID
          RUN_SERVICE:
            ref: .CLOUD_RUN_ASSET_NAME
          RUN_REVISION:
            ref: .CLOUD_RUN_ASSET_NAME
          RUN_REGION:
            ref: .CLOUD_RUN_REGION
          FORMAT: "json"
